SELECT TOP (1000) [tr_part]
      ,[tr_type]
      ,[tr_loc]
      ,[tr_nbr]
      ,[tr_addr]
      ,[tr_rmks]
      ,[tr_mtl_std]
      ,[tr_price]
      ,[tr_trnbr],
	  [tr_nbr]
      ,[tr_gl_amt]
      ,[tr_lot]
      ,[tr_qty_loc]
      ,[tr_serial]
      ,[tr_effdate]
      ,[tr_prod_line]
      ,[tr_line]
      ,[tr_site]
      ,[tr_status]
      ,[tr_ref]
      ,[tr_msg]
      ,[tr_program]
      ,[tr_wod_op]
      ,[tr_ship_date]
  FROM [QADEE2798].[dbo].[tr_hist]
  WHERE [tr_type] IN ('iss-wo','iss-tr','rct-tr','iss-scrp','rct-po','iss-unp','cyc-rcnt','rct-wo','iss-so') and [tr_date] > '2024-01-01' and [tr_loc]='wip';