SELECT [cov_id]
      ,[cov_btch_nbr]
      ,[cov_cust_code]
      ,[cov_hu]
      ,[cov_ifs]
      ,[cov_pi]
      ,[cov_valid]
      ,[cov_ws_code]
      ,[cov_cov_nbr]

      ,[cov_set_nbr]
      ,[cov_set_ver]
      ,[cov_timestamp]
      ,[cov_pt_counter]
      ,[cov_counter]
      ,[cov_customer_item]
      ,[cov_pck_name]
      ,[cov_planned_qty]

      ,[cov_shift]
      ,[cov_ws_name]
    
  FROM [TCIS_MES2_265].[dbo].[cov_hist]
