SELECT [schd_nbr] as [SO]
      ,[schd_line] as [SO Line]
      ,[schd_rlse_id] as [Release ID]
      ,[schd_date] as [Date]
      ,[schd_discr_qty] as [Discrete Qty]
      ,[schd_interval] as [Schedule Interval]
      ,[schd_cum_qty] as [Cum Shipped]
      ,[schd_ship_qty] as [Shipped Qty]
      ,[schd_all_qty]
  FROM [QADEE2798].[dbo].[active_schd_det]
  order by [schd_nbr],[schd_line],[schd_date];