SELECT [sch_type]
      ,[sch_nbr]
      ,[sch_line]
      ,[sch_rlse_id]
      ,[sch_cr_date]
      ,[sch_cr_time]
      ,[sch_ship]
      ,[sch_sd_pat]
      ,[sch_pcr_qty]
      ,[sch_pcs_date]
      ,[sch__chr04]
      ,[sch_lr_asn[1]]]
      ,[sch_lr_date[1]]]
      ,[sch_lr_qty[1]]]
      ,[sch_lr_cum_qty[1]]]
      ,[sch_eff_start]
      ,[sch_eff_end] 
      ,[sch_from_pid]
  FROM [QADEE2798].[dbo].[sch_mstr]
  where [sch__chr04] is null;