SELECT
[tr_part] as [Item Number]
      ,[tr_type] as [Transaction Type]
      ,[tr_loc] as [Location]
      ,[tr_loc_begin] as [Begining Qty]
      ,[tr_begin_qoh] as [Qty on Hand]
      ,[tr_qty_chg] as [Qty Change]
      ,[tr_last_date] as [Last Transaction Date]
      ,[tr_nbr]
      ,[tr_so_job]
      ,[tr_addr]
      ,[tr_rmks]
      ,[tr_trnbr]
      ,[tr_lot]
      ,[tr_qty_loc]
      ,[tr_userid]
      ,[tr_effdate]
      ,[tr_prod_line]
      ,[tr_line]
      ,[tr_time]
      ,[tr_site]
      ,[tr_status]
      ,[tr_ref]
    ,[tr_program]
      ,[tr_wod_op]
      ,[tr_ship_date]
  FROM [QADEE2798].[dbo].[tr_hist]
    where [tr_type] not in ('cst-adj','cyc-cnt','iss-chl','rct-chl','cyc-err','ord-so','cum-rres','rct-adj','cum-radj','cum-sadj','iss-tr','rct-tr')
	and [tr_effdate] > '2024-07-01';